name: Publish

on:
  push:
    branches:
      - master

env:
  LC_ALL: en_US.UTF-8

jobs:
  PublishSnapshots:
    name: Publish Snapshots
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        run: |
          ./publish.sh snapshots